syntax = "proto3";

package model;

option go_package = "github.com/NodePath81/mspm/proto/generated/generated_go";

message Account{
    string user_id = 1;
    string username = 2 ;
    string password = 3;
}

message TokenInfo{
    string user_id = 1;
    uint32 token_version = 3;
}

message ImageTags{
    repeated string user_specified_tags = 1;
    repeated string auto_generated_tags = 2;
}

message ImageMetadata {
    string image_id = 1;
    string user_id = 2;
    reserved 3;
    repeated float embedding = 4;
    ImageTags tags = 5;
    int64 uploaded_at = 6;
    reserved 7;
    string file_name = 8;
    optional string category = 9;
    uint32 width = 10;
    uint32 height = 11;
    string file_type = 12;
}